### ISSUE TITLE
Not so ethical...

### ISSUE THREAD

**Issue by xClaudi0** [zAlweNy26/pokemon-scrapers#1]
As the title says...I don't think that scraping is a fair behaviour...

**Comment by zAlweNy26** [comment]
@xClaudi0 as the guidelines of the [European Commission](https://ec.europa.eu/eurostat/documents/272892/12032198/Guidelines-web-scraping-HICP-11-2020.pdf/) say, we are not violeting any copyright since we give credits and not using any sort of authentication bypass (since there isn't one on Serebii.net). So I'll close this issue.
